config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  
  root "users#index"
   post '/api/v1/auth/login', to: 'authentication#login'
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users, only: [:show, :create] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  devise_for :users,
   path: '',
   path_names: {
     sign_in: 'login',
     sign_out: 'logout',
     password: 'secret',
     confirmation: 'verification',
     registration: 'register',
     sign_up: 'signup'
   }

 resources :users, only: [:index, :show] do
   resources :posts, only: [:index, :show, :new, :create, :destroy] do
     resources :comments, only: [:new, :create, :destroy]
     resources :likes, only: [:new, :create]
   end
 end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates_presence_of :name, presence: true
  validates :posts_counter, presence: true,
                            numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  validates :email, confirmation: true
  has_many :posts, foreign_key: 'user_id', dependent: :destroy
  has_many :comments, foreign_key: 'user_id', dependent: :destroy
  has_many :likes, foreign_key: 'user_id', dependent: :destroy

  def latest_three_post
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_action :authenticate_request, only: [:create]
  before_action :set_user, only: [:show]

  def show
    render json: { message: "Welcome #{@user.name}" }
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render json: @user, status: :created
    else
      render json: { message: 'Something is wrong', errors: @user.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.permit(:name, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_request
  def index
    @users = User.all
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end
end

app/views/users/index.html.erb
<ul class="userProfile">
  <% @users.each do |user|%>
    <%= link_to user do %>
      <ul class="User">
        <li class="userImage">
          <img src=<%= user.photo %> alt="UserImage">
        </li>
        <li class="userName"><%= user.name %></li>
        <li class="userNumberOfposts">Post:<%= user.posts_counter %></li>
      </ul>
      <% end %>
  <% end %>
</ul>

app/views/users/show.html.erb
<section class="singleUser--section">
  <ul class="userProfile">
    <ul class="User">
      <li class="userImage">
        <img src=<%= @user.photo %> alt="UserImage"></li>
      <li class="userName"><%= @user.name %></li>
      <li class="userNumberOfposts">Post:<%= @user.posts_counter %></li>
    </ul>
    <li class="bio">
      <h3 class="bioTit">Bio<h3>
      <p><%= @user.bio %><p>
    </li>
  </ul>

  <ul class="userPosts">
    <h1 class="recentPosts">Recent Posts</h1>
    <% @user.latest_three_post.each do |post| %>
      <%= link_to user_post_path(user_id: post.user_id, id: post.id) do %>
        <ul class="ul--post">
          <li class="li--post">
            <h4><%= post.title%></h4>
            <h4><%= post.text%></h4>
            <div class="comment--likes">
              <span>Comments: <%= post.comments_counter %></span>
              <span>Likes: <%= post.likes_counter %> </span>
            </div>
          </li>
        </ul>
      <% end %>
    <% end %>
    <%= link_to "See All Posts", user_posts_path(user_id: @user.id), class: "allPosts" %>
    <%= link_to "See all users", users_path, class: "allPosts" %>
    <%= link_to "Add a post", new_user_post_path(user_id: @user.id), class: "allPosts" %>
    </ul>
</section>