config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  
  root "users#index"
   post '/api/v1/auth/login', to: 'authentication#login'
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users, only: [:show, :create] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  devise_for :users,
   path: '',
   path_names: {
     sign_in: 'login',
     sign_out: 'logout',
     password: 'secret',
     confirmation: 'verification',
     registration: 'register',
     sign_up: 'signup'
   }

 resources :users, only: [:index, :show] do
   resources :posts, only: [:index, :show, :new, :create, :destroy] do
     resources :comments, only: [:new, :create, :destroy]
     resources :likes, only: [:new, :create]
   end
 end
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, length: { maximum: 250 }
  validates :likes_counter, presence: true,
                            numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :comments_counter, presence: true,
                               numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :posts_count
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def posts_count
    user.increment!(:posts_counter)
  end

  private :posts_count
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  before_action :authenticate_request

  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(['author_id = :id', { id: params[:user_id].to_s }])

    render json: JSON.pretty_generate(@posts.as_json)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes(:posts).find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to user_path(id: @post.user_id)
      flash[:notice] = 'Posted successfully!'
    else
      render :new
      flash[:alert] = 'No post yet'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_posts_path(params[:user_id])
    authorize! :destroy, @post
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
  private :post_params
end

app/views/posts/form.html.erb
<section>
  <h1 class="users-title">Add a new post</h1>
  <%= form_with model: @post, url: user_posts_path, class: "" do |form| %>
    <%= form.label :title %> <br>
    <%= form.text_field :title %> <br>
    <%= form.label :text %> <br>
    <%= form.text_area :text , cols: 30, rows: 10 %> <br>
    <%= form.submit "Submit", class: "btn" %>
  <% end %>
</section>

app/views/posts/index.html.erb
<section class="singleUser--section">
<ul class="userProfile">
<h1> <%= @user.name %> posts </h1>
    <ul class="User">
      <li class="userImage">
        <img src=<%= @user.photo %> alt="UserImage"></li>
      <li class="userName"><%= @user.name %></li>
      <li class="userNumberOfposts">Posts:<%= @user.posts_counter %></li>
    </ul>
  </ul>
</section>

<section class="singleUserPosts--section">
  <ul class="this">
    <% @posts.each do |post| %>
      <%= link_to user_post_path(user_id: post.user_id, id: post.id) do %>
        <li class="singlePost">
          <div class="singlePot">
            <h3><%= post.title %></h3>
            <p><%= post.text %></p>
            <div class="com--Lik--counter">
              <span>Comments: <%= post.comments_counter %></span>
              <span>Likes: <%= post.likes_counter %> </span>
            </div>
          </div>
          <div class="singleComment">
            <h4>Comments:</h4>
            <ul>
              <% post.recent_comments.includes(:user).each do |comment| %>
                <p><%= comment.user.name %>: <%= comment.text %></p>
              <% end %>
            </ul>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</section>

app/views/posts/new.html.erb
<section>
  <h1 class="users-title">Add a new post</h1>
  <%= form_with model: @post, url: user_posts_path, data: {turbo: false}, method: :post, class: "" do |form| %>
    <%= form.label :title %> <br>
    <%= form.text_field :title %> <br>
    <%= form.label :text %> <br>
    <%= form.text_area :text , cols: 30, rows: 10 %> <br>
    <%= form.submit "Submit", class: "btn" %>
  <% end %>
</section>

app/views/posts/show.html.erb
<ul class="singleUserOnePost">
<%= link_to "Back to posts", user_path(id: @post.user_id), class: "addCom" %>
  <div class="singlePost">
    <h4><%= @post.title %></h4>
    <p><%= @post.text %></p>
    <% if can? :destroy, @post %>
    <%= button_to 'Delete post', user_post_path(@post.user, @post.id), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-outline-dark' %>
  <% end %>
  </div>

  <div class="right">
    <span>Comments: <%= @post.comments_counter %></span>
    <span>Likes: <%= @post.likes_counter %> </span>
  </div>
  <div class="singleComment">
    <h4>Comments:</h4>
    <ul>
      <% @post.comments.includes(:user).each do |comment| %>
        <p><%= comment.user.name %>: <%= comment.text %></p>
           <% if can? :destroy, comment %>
            <%= button_to 'Delete comment', user_post_comment_path(@post.user, @post.id), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-outline-dark' %>
        <% end %>
      <% end %>
    </ul>
  </div>

  <div class="addNewdiv">
    <%= link_to "comment", new_user_post_comment_path(user_id: @post.user_id, post_id: @post.id ), class: "addCom" %>
    <%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |form| %>
      <%= form.submit "Like post", class: "addCom" %>
    <% end %>
  </div>
</ul>